
    // ----------------------------------------------
    // generated by create-contract-cli from ./res/test/rust/staking-pool-factory/src/lib.rs
    // ---------------------------------------------

    const color = require("./util/color.js");
    const nearCli = require("./util/SpawnNearCli.js");
    const options = require("./CLIOptions.js");
    const cliConfig = require("./CLIConfig.js");

    // name of this script
    const nickname = cliConfig.nickname;

    // one function for each pub fn in the contract
    // get parameters by consuming from CommandLineParser
    class ContractAPI {

        // this.view helper function
        view(command/*:string*/, fnJSONParams/*?:any*/) /*:string*/ {
            return nearCli.view(cliConfig.contractAccount, command, fnJSONParams, options)
        }
        // this.call helper function
        call(command/*:string*/, fnJSONParams/*?:any*/) /*:string*/ {
            return nearCli.call(cliConfig.contractAccount, command, fnJSONParams, options)
        }
    
    
  new_HELP(){ return `
   Initializes the staking pool factory with the given account ID of the staking pool whitelist
   contract.
  #[init]
  
  usage:
  > factory new 
  `};
  
  new(a /*:CommandLineArgs*/) /*:void*/{
    
    //--these are some examples on how to consume arguments
    //const toAccount = a.consumeString("to Account")
    //const argumentJson = a.consumeJSON("{ account:userAccount, amount:xxN }")
    
    //--new has no arguments, if you add some, uncomment the following line and send the params in this.call/view
    //const fnJSONParams = a.consumeJSON("{ x:0, y:1, z:3 }")
    
    a.noMoreArgs() // no more positional args should remain
    
    this.call("new")
    
  }
  
  get_min_attached_balance_HELP(){ return `
   Returns the minimum amount of tokens required to attach to the function call to
   create a new staking pool.
  
  usage:
  > factory get_min_attached_balance 
  `};
  
  get_min_attached_balance(a /*:CommandLineArgs*/) /*:string*/{
    
    //--these are some examples on how to consume arguments
    //const toAccount = a.consumeString("to Account")
    //const argumentJson = a.consumeJSON("{ account:userAccount, amount:xxN }")
    
    //--get_min_attached_balance has no arguments, if you add some, uncomment the following line and send the params in this.call/view
    //const fnJSONParams = a.consumeJSON("{ x:0, y:1, z:3 }")
    
    a.noMoreArgs() // no more positional args should remain
    
    return this.view("get_min_attached_balance")
    
  }
  
  get_number_of_staking_pools_created_HELP(){ return `
   Returns the total number of the staking pools created from this factory.
  
  usage:
  > factory get_number_of_staking_pools_created 
  `};
  
  get_number_of_staking_pools_created(a /*:CommandLineArgs*/) /*:string*/{
    
    //--these are some examples on how to consume arguments
    //const toAccount = a.consumeString("to Account")
    //const argumentJson = a.consumeJSON("{ account:userAccount, amount:xxN }")
    
    //--get_number_of_staking_pools_created has no arguments, if you add some, uncomment the following line and send the params in this.call/view
    //const fnJSONParams = a.consumeJSON("{ x:0, y:1, z:3 }")
    
    a.noMoreArgs() // no more positional args should remain
    
    return this.view("get_number_of_staking_pools_created")
    
  }
  
  create_staking_pool_HELP(){ return `
   Creates a new staking pool.
   - 'staking_pool_id' - the prefix of the account ID that will be used to create a new staking
      pool account. It'll be prepended to the staking pool factory account ID separated by dot.
   - 'owner_id' - the account ID of the staking pool owner. This account will be able to
      control the staking pool, set reward fee, update staking key and vote on behalf of the
       pool.
   - 'stake_public_key' - the initial staking key for the staking pool.
   - 'reward_fee_fraction' - the initial reward fee fraction for the staking pool.
  #[payable]
  
  usage:
  > factory create_staking_pool { staking_pool_id: String, owner_id: AccountId, stake_public_key: Base58PublicKey, reward_fee_fraction: RewardFeeFraction }
  `};
  
  create_staking_pool(a /*:CommandLineArgs*/) /*:void*/{
    
    //function is #payable, --amount option is required
    a.requireOptionWithAmount(options.amount,'N'); //contract fn is payable, --amount expressed in N=NEARS is required
    //--these are some examples on how to consume arguments
    //const toAccount = a.consumeString("to Account")
    //const argumentJson = a.consumeJSON("{ account:userAccount, amount:xxN }")
    
    //get fn arguments as JSON
    const fnJSONParams = a.consumeJSON("{ staking_pool_id: String, owner_id: AccountId, stake_public_key: Base58PublicKey, reward_fee_fraction: RewardFeeFraction }")
    
    a.noMoreArgs() // no more positional args should remain
    
    this.call("create_staking_pool",fnJSONParams)
    
  }
  
  on_staking_pool_create_HELP(){ return `
   Callback after a staking pool was created.
   Returns the promise to whitelist the staking pool contract if the pool creation succeeded.
   Otherwise refunds the attached deposit and returns 'false'.
  
  usage:
  > factory on_staking_pool_create { staking_pool_account_id: AccountId, attached_deposit: U128, predecessor_account_id: AccountId }
  `};
  
  on_staking_pool_create(a /*:CommandLineArgs*/) /*:void*/{
    
    //--these are some examples on how to consume arguments
    //const toAccount = a.consumeString("to Account")
    //const argumentJson = a.consumeJSON("{ account:userAccount, amount:xxN }")
    
    //get fn arguments as JSON
    const fnJSONParams = a.consumeJSON("{ staking_pool_account_id: AccountId, attached_deposit: U128, predecessor_account_id: AccountId }")
    
    a.noMoreArgs() // no more positional args should remain
    
    this.call("on_staking_pool_create",fnJSONParams)
    
  }
  
}
module.exports = ContractAPI;
